#ifndef dataformtats_raw_fed_edm__WrapperBase_h
#define dataformtats_raw_fed_edm__WrapperBase_h
namespace edm {
class WrapperBase;
} // end of namespace.

#include "Rtypes.h"
#include "edm__ViewTypeChecker.h"

namespace edm {
class WrapperBase : public edm::ViewTypeChecker {

public:
// Nested classes declaration.

public:
// Data Members.

   WrapperBase() {}
   WrapperBase(const WrapperBase & )
   {}
   virtual ~WrapperBase() {}

   ClassDef(WrapperBase,5); // Generated by MakeProject.
};
} // namespace

ClassImp(edm::WrapperBase)
#endif
