#ifndef dataformtats_raw_fed_edm__ViewTypeChecker_h
#define dataformtats_raw_fed_edm__ViewTypeChecker_h
namespace edm {
class ViewTypeChecker;
} // end of namespace.

#include "Rtypes.h"

namespace edm {
class ViewTypeChecker {

public:
// Nested classes declaration.

public:
// Data Members.

   ViewTypeChecker() {}
   ViewTypeChecker(const ViewTypeChecker & ) {}
   virtual ~ViewTypeChecker() {}

   ClassDef(ViewTypeChecker,3); // Generated by MakeProject.
};
} // namespace

ClassImp(edm::ViewTypeChecker)
#endif
