#ifndef dataformtats_raw_fed_FEDRawDataCollection_h
#define dataformtats_raw_fed_FEDRawDataCollection_h

#include <vector>
#include "FEDRawData.h"

namespace edm {
    class DoNotRecordParents {

        ClassDef(DoNotRecordParents, 12);
    };
}

ClassImp(edm::DoNotRecordParents)

class FEDRawDataCollection : public edm::DoNotRecordParents {
public:
    std::vector<FEDRawData> data_;       //the raw data
    FEDRawDataCollection() {}
    FEDRawDataCollection(const FEDRawDataCollection & rhs) :
       data_(rhs.data_) 
    {}
    virtual ~FEDRawDataCollection()
    {}
    
    // for IO
    ClassDef(FEDRawDataCollection, 12); // Generated by MakeProject.
};

ClassImp(FEDRawDataCollection)

#endif
