#ifndef edm__Wrapper_FEDRawDataCollection__h
#define edm__Wrapper_FEDRawDataCollection__h
class FEDRawDataCollection;
namespace edm {
template <typename T0> class Wrapper;
template <> class Wrapper<FEDRawDataCollection>;
} // end of namespace.

#include "Rtypes.h"
#include "FEDRawDataCollection.h"
#include "edm__WrapperBase.h"

namespace edm {
template <typename T0> class Wrapper;
template <> class Wrapper<FEDRawDataCollection> : public edm::WrapperBase {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        present;     //
   FEDRawDataCollection obj;         //

   Wrapper() {}
   Wrapper(const Wrapper & rhs) :
       present(rhs.present), obj(rhs.obj)
    {}
   virtual ~Wrapper() {}

   ClassDef(Wrapper,4); // Generated by MakeProject.
};
} // namespace

ClassImp(edm::Wrapper<FEDRawDataCollection>)
#endif
