//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Mar 13 21:43:07 2018 by ROOT version 6.11/03)
//      from the StreamerInfo in file 14299455-0DBA-E711-A0D4-02163E019C73_numEvent100.root
//////////////////////////////////////////////////////////


#ifndef edm__ViewTypeChecker_h
#define edm__ViewTypeChecker_h
namespace edm {
class ViewTypeChecker;
} // end of namespace.

#include "Rtypes.h"

namespace edm {
class ViewTypeChecker {

public:
// Nested classes declaration.

public:
// Data Members.

   ViewTypeChecker() {}
   ViewTypeChecker(const ViewTypeChecker & ) {}
   virtual ~ViewTypeChecker() {}

   ClassDef(ViewTypeChecker,3); // Generated by MakeProject.
};
} // namespace

ClassImp(edm::ViewTypeChecker)
#endif
